default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: rails_saju_development
  url: 

test:
  <<: *default
  database: rails_saju_test
  url: 

production:
  # 모든 기능을 하나의 DB(Render DB)로 통일
  primary:
    <<: *default
  cache:
    <<: *default
  queue:
    <<: *default
  cable:
    <<: *default