default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: rails_saju_development
  url: 

test:
  <<: *default
  database: rails_saju_test
  url: 

production:
  primary:
    <<: *default
  cache:
    <<: *default
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    migrations_paths: db/queue_migrate  # ðŸ‘ˆ ì—¬ê¸°ê°€ ì¤‘ìš”! (ìž‘ì—… ëŒ€ê¸°ì‹¤ ìœ„ì¹˜)
  cable:
    <<: *default
    migrations_paths: db/cable_migrate  # ðŸ‘ˆ ì—¬ê¸°ê°€ ì¤‘ìš”! (í†µì‹ ì‹¤ ìœ„ì¹˜)