default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: rails_saju_development
  url: 

test:
  <<: *default
  database: rails_saju_test
  url: 

production:
  <<: *default
  # primary, queue, cable... 이런 거 다 지우고 딱 기본만 남김!